#!/usr/bin/env python
# coding: utf-8

# In[3]:



#import packages AND connection to MongoDB instance
import pymongo
import json
client=pymongo.MongoClient()


# In[ ]:





# In[4]:


#connecting to client
client=pymongo.MongoClient('localhost',27017)


# In[5]:


#database creation
database=client["meal_info"]


# In[6]:


#creating collection 
collection=database["meal_data1"]


# In[29]:


collection.count_documents({})


# In[30]:


#to find the documents
for i in collection.find():
   print(i)


# In[31]:


#inserting a single document
doc={"meal_id":2344,"category":"rice","cuisine":"indian"}
collection.insert_one(doc)


# In[32]:


#inserting many documents
multi_docs=[{"meal_id":2349,"category":"ragi","cuisine":"indian"},
            {"meal_id":2374,"category":"wheat","cuisine":"indian"},
            {"meal_id":2444,"category":"dosa","cuisine":"indian"}]
collection.insert_many(multi_docs)


# In[33]:


collection.count_documents({})


# In[35]:


#finding all documents
for i in collection.find():
    print(i)


# In[36]:


#limiting to 5 documents
for i in collection.find().limit(5):
    print(i)


# In[41]:


#updating many documents
mydoc={"cuisine":{"$regex":"^Thai"}}
new_doc={"$set":{"cuisine":"Thailand"}}
result=collection.update_many(mydoc,new_doc)
print(result)


# In[42]:


#finding all documents
for i in collection.find():
    print(i)


# In[43]:


#deleting single document
print(collection.delete_one({'meal_id': 2444, 'category': 'PURE_VEG', 'cuisine': 'indian'}))


# In[44]:


#finding all documents
for i in collection.find():
    print(i)


# In[57]:


#deleting many documents
collection.delete_many({ 'category': 1,'cuisine':1})


# #finding all documents
# for i in collection.find():
#     print(i)

# In[ ]:





# In[38]:


#sorting 
for i in collection.find({},{"cuisine":1,"_id":0}).sort("cuisine"):
    print(i)


# In[51]:


#droping the database
print(collection.meal_data1.drop())


